### ISSUE TITLE
Thank a VERY large REPO

### ISSUE THREAD

**Issue by orefalo** [SilvanCodes/svelte-layout-components#6]
I stopped at 80GB download, 
I would recommend to add the --depth 1 in the git clone command line
and to rewrite branch history to prune the junk

**Comment by SilvanCodes** [comment]
That seems very odd!
Can you please explain which command you executed?

I could not reproduce your issue when running either
```
git clone git@github.com:SilvanCodes/svelte-layout-components.git
Cloning into 'svelte-layout-components'...
remote: Enumerating objects: 568, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 568 (delta 2), reused 0 (delta 0), pack-reused 561
Receiving objects: 100% (568/568), 821.13 KiB | 1.77 MiB/s, done.
Resolving deltas: 100% (380/380), done.
```
which took 2 seconds to run nor when running
```
npx degit SilvanCodes/svelte-layout-components svelte-layouts
Need to install the following packages:
  degit
Ok to proceed? (y) y
> cloned SilvanCodes/svelte-layout-components#HEAD to svelte-layouts
```
which took 12 seconds to run.

**Comment by orefalo** [comment]
Weird indeed, 
was on a poor connection at the time and can confirm it's a non issue.
Thank you

**Comment by SilvanCodes** [comment]
Thank you for checking again. 👍🏼
